root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./bin/app.exe ./cmd/main.go"
bin = "bin/app.exe"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = []
include_dir = []
include_file = []
exclude_file = []
exclude_regex = []
exclude_unchanged = true
follow_symlink = true
log = "air.log"
poll = false
poll_interval = 500 # ms
delay = 0 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500 # nanosecond
rerun = false
rerun_delay = 500

[log]
time = false
main_only = false
silent = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true

[proxy]
enabled = false
proxy_port = 8090
app_port = 8080