services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_clean_app
    ports:
      - "8080:8080" # Maps container's port 8080 to host's port 8080
    depends_on:
      - db # Ensures the database service is started before the Go app
    networks:
      - app-network
    volumes:
      - .:/app # Bind mount the project directory to the container for live reloading

  db:
    image: postgres:13
    container_name: go_clean_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pelter
    ports:
      - "5432:5432" # Exposes PostgreSQL on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data in a Docker volume
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
